export { default as Switch } from './wySwitch.vue'
export { default as Button } from './wyButton.vue'
export { default as Tabs } from './wyTabs.vue'
export { default as Tab } from './wyTab.vue'
export { default as Dialog } from './wyDialog.vue'
export { openDialog as openDialog } from './openDialog'
export { default as Input } from './wyInput.vue'
